# Autogenerated by nbdev

d = { 'settings': { 'doc_baseurl': '/paragraph_-detective',
                'doc_host': 'https://jean-kunz.github.io',
                'git_url': 'https://github.com/jean-kunz/paragraph_-detective',
                'lib_path': 'paragraph_detective'},
  'syms': {'paragraph_detective.model': {}}}
