# Autogenerated by nbdev

d = { 'settings': { 'doc_baseurl': '/paragraph_-detective',
                'doc_host': 'https://jean-kunz.github.io',
                'git_url': 'https://github.com/jean-kunz/paragraph_-detective',
                'lib_path': 'paragraph_detective'},
  'syms': { 'paragraph_detective.data_prep': { 'paragraph_detective.data_prep.create_line_features': ( 'data_prep.html#create_line_features',
                                                                                                       'paragraph_detective/data_prep.py'),
                                               'paragraph_detective.data_prep.prepare_data_from_doc': ( 'data_prep.html#prepare_data_from_doc',
                                                                                                        'paragraph_detective/data_prep.py')},
            'paragraph_detective.model': { 'paragraph_detective.model.clean_doc_paragraphs': ( 'model.html#clean_doc_paragraphs',
                                                                                               'paragraph_detective/model.py'),
                                           'paragraph_detective.model.df_to_x_y': ('model.html#df_to_x_y', 'paragraph_detective/model.py'),
                                           'paragraph_detective.model.get_model': ( 'model.html#get_model',
                                                                                    'paragraph_detective/model.py')}}}
