# Autogenerated by nbdev

d = { 'settings': { 'doc_baseurl': '/paragraph_-detective',
                'doc_host': 'https://jean-kunz.github.io',
                'git_url': 'https://github.com/jean-kunz/paragraph_-detective',
                'lib_path': 'paragraph_detective'},
  'syms': { 'paragraph_detective.model': { 'paragraph_detective.model.create_line_features': ( 'model.html#create_line_features',
                                                                                               'paragraph_detective/model.py'),
                                           'paragraph_detective.model.df_to_x_y': ('model.html#df_to_x_y', 'paragraph_detective/model.py'),
                                           'paragraph_detective.model.do_prepare_train_data_grp': ( 'model.html#do_prepare_train_data_grp',
                                                                                                    'paragraph_detective/model.py'),
                                           'paragraph_detective.model.load_model': ( 'model.html#load_model',
                                                                                     'paragraph_detective/model.py'),
                                           'paragraph_detective.model.prepare_paragraph_from_txt_lines': ( 'model.html#prepare_paragraph_from_txt_lines',
                                                                                                           'paragraph_detective/model.py'),
                                           'paragraph_detective.model.prepare_train_data': ( 'model.html#prepare_train_data',
                                                                                             'paragraph_detective/model.py'),
                                           'paragraph_detective.model.train_model': ( 'model.html#train_model',
                                                                                      'paragraph_detective/model.py')}}}
